In [1]:
import pandas as pd

df = pd.read_csv("covid-data.csv")
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3524: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,24-02-20,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25-02-20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26-02-20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27-02-20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28-02-20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [2]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,1.660100e+05,1.658450e+05,1.638900e+05,1.482860e+05,148302.000000,146182.000000,165221.000000,165056.000000,163107.000000,147510.000000,...,106816.000000,105298.000000,67872.000000,125354.000000,160823.00000,138470.000000,6.078000e+03,6078.000000,6078.000000,6078.000000
mean,2.181535e+06,9.624379e+03,9.650398e+03,4.699081e+04,130.638252,131.984235,34149.937389,183.419836,183.140198,546.865218,...,10.883311,32.768599,50.908481,3.059853,73.78373,0.728430,3.899161e+04,9.582009,15.804225,1035.395150
std,1.138868e+07,6.402562e+04,6.259368e+04,2.016549e+05,560.340589,546.261209,61842.104129,749.780464,578.708240,825.992171,...,10.678178,13.697863,32.192122,2.474018,7.46065,0.149943,1.088362e+05,16.258235,29.521194,1482.622037
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.001000,0.000000,0.000000,0.000000,...,0.100000,7.700000,1.188000,0.100000,53.28000,0.394000,-3.772610e+04,-28.450000,-95.920000,-1826.595723
25%,2.319000e+03,1.000000e+00,7.143000e+00,8.500000e+01,0.000000,0.143000,695.368000,0.029000,1.734000,20.325000,...,1.900000,21.400000,19.351000,1.300000,69.66000,0.609000,-4.415000e+01,-0.450000,-0.560000,-18.981390
50%,3.010950e+04,8.000000e+01,1.104290e+02,8.170000e+02,2.000000,2.429000,5344.915000,11.781000,20.225000,144.946000,...,6.300000,33.100000,49.839000,2.400000,75.12000,0.748000,3.585550e+03,6.300000,7.380000,512.797169
75%,3.287078e+05,1.069000e+03,1.168821e+03,7.739000e+03,19.000000,20.857000,43919.924000,107.087000,129.667500,792.482000,...,19.600000,41.300000,83.241000,4.200000,79.19000,0.848000,2.639225e+04,14.640000,22.465000,1699.146465
max,2.769339e+08,2.830540e+06,2.322156e+06,2.493233e+06,11059.000000,8392.286000,706541.904000,51427.491000,16052.608000,6366.179000,...,44.000000,78.100000,100.000000,13.800000,86.75000,0.957000,1.163660e+06,111.010000,375.000000,9573.960130